FROM alpine:latest

RUN apk add --no-cache apache2 \
    && echo "Hello from the EC2 instance $(hostname -f)." > /var/www/localhost/htdocs/index.html
RUN rc-service apache2 start
RUN rc-update add apache2


ENTRYPOINT ["/usr/bin/httpd.sh"]
EXPOSE 80
EXPOSE 443