---
- name: Start docker service
  service:
    name: docker
    state: started
  become: yes

- name: Build an image and push
  community.docker.docker_image:
    build:
      path: files
      dockerfile: files/dockerfile
    name: simple_web
    tag: v1
    source: build
  become: yes

- name: Create container
  community.docker.docker_container:
    name: mywebapp
    image: simple_web/apache
    state: present
    source: 
    exposed_ports:
      - 80
      - 443
    volumes_from:
      - mydata