---
- name: Start docker service
  service:
    name: docker
    state: started
  become: yes

- name: Build an image and push
  community.docker.docker_image:
    build:
      path: /home/ubuntu/ansible_docker_example/roles/tools/files
    name: simple_web
    source: build
  become: yes

- name: Create container
  community.docker.docker_container:
    name: mywebapp
    image: simple_web
    state: started
    exposed_ports:
      - 80
      - 443
  become: yes