---
- name: Install pre-requisites
  apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3-pip
    state: present
  become: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    filename: docker
    state: present
  become: yes

- name: Update apt and install docker-ce
  apt: 
    pkg:
    - docker-ce
    - docker-ce-cli 
    - containerd.io 
    state: latest
    update_cache: yes
  become: yes

- name: Install Docker Module for Python
  pip:
    name: docker
  become: yes












